name: Deploy da Aplicação

on:
  push:
    branches:
      - main  # Substitua "main" pelo nome da sua branch principal

jobs:
  deploy:
    name: Deploy da Aplicação
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Substitua pela versão desejada do Node.js

      - name: Instalar Dependências
        run: npm install  # Substitua por comando de instalação de dependências do seu projeto

      - name: Construir a Aplicação
        run: npm run build  # Substitua pelo comando de build da sua aplicação

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v2
        with:
          host: seu_servidor_ssh
          username: seu_usuario_ssh
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Configure a chave SSH como um segredo no GitHub
          script: |
            # Comandos para fazer o deploy da aplicação
            # Substitua "seu_servidor_ssh" e "seu_usuario_ssh" pelas suas informações

      # Outras etapas que você deseja adicionar, como notificações de sucesso ou falha



